name: 'Docker Image Deploy In Rancher1.6'
description: 'Action to deploy docker image in rancher1.6'
author: 'turbo'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  serviceInfoApiUrl:
    description: "API Url of your rancher servcie , you can get in rancher UI,like: https://rancher.test.com/v2-beta/projects/1a22/services/1s33"
    required: true
  rancherAccessKey:
    description: "API Access key created in Rancher"
    required: true
  rancherSecretKey:
    description: "API Secret key created in Rancher"
    required: true
  dockerImage:
    description: "Docker Image, like: test/nginx:latest"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'