name: 'Docker Image Deploy In Rancher1.6'
description: 'Action to deploy docker image in rancher1.6'
author: 'Giau. Tran Minh & turbo'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  rancherUrlApi:
    description: "API Url of your rancher project workload"
    required: true
  rancherAccessKey:
    description: "API Access key created in Rancher"
    required: true
  rancherSecretKey:
    description: "API Secret key created in Rancher"
    required: true
  serviceName:
    description: "Name of your service on rancher cluster what you want deploy"
    required: true
  dockerImage:
    description: "Docker Image"
    required: true
  projectName:
    description: "Name of project"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'